version: "3"

services:
  aruco-distance:
    build: ArucoDistance/
    environment:
    # It needs for GUI
      - DISPLAY=$DISPLAY
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    #command: python3 test.py # This program is for camera tests
    command: python3 ArucoDistance.py
  
  # Uncomment next code when there will be FetchingArucoMarks realisation
  # fetching-aruco-marks:
  #   build: FetchingArucoMarks/
  #   environment:
  #     - DISPLAY=$DISPLAY
  #   devices:
  #    - /dev/video0:/dev/video0
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   networks:
  #     - zeromq-network
  #   command: ./main

  # networks:
  #   zeromq-network:
  #     name: zeromq-network
  #     driver: bridge