FROM gcc:latest as build

# Installing OpenCV
RUN apt-get update && \
    apt-get install -y \
        libopencv-dev \
        cmake

# Installing ZeroMQ
RUN set -ex;                                                                      \
    apt-get update;                                                               \
    apt-get install -y cmake libzmq3-dev;                                         \
    mkdir -p /usr/src;                                                            \
    cd /usr/src;                                                                  \
    curl -L https://github.com/zeromq/cppzmq/archive/v4.6.0.tar.gz | tar -zxf -;  \
    cd /usr/src/cppzmq-4.6.0;                                                     \
    cmake -D CPPZMQ_BUILD_TESTS:BOOL=OFF .; make; make install

# Adding project files in container   
ADD . /app

# Builing a project
WORKDIR /app/build

RUN cmake ../ && \
    make
# ENTRYPOINT ["./main"]

